In [1]:
import numpy as np

In [2]:
#1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。

In [8]:
np.linspace(0, 20, num=21, endpoint=True)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20.])

In [9]:
#2.呈上題，將以上數列取出偶數。


In [38]:
a = np.arange(21)
a[2:21:2]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [16]:
#3.呈1題，將數列取出3的倍數。


In [39]:
a = np.arange(21)

In [40]:
a[3:21:3]

array([ 3,  6,  9, 12, 15, 18])