In [2]:
import numpy as np

In [3]:
english_score = np.array([55,89,76,65,48,70])
math_score = np.array([60,85,60,68,55,60])
chinese_score = np.array([65,90,82,72,66,77])

In [4]:
np.logical_and(math_score, chinese_score)

array([ True,  True,  True,  True,  True,  True])

In [8]:
np.logical_and(np.greater(chinese_score, math_score),np.greater(chinese_score, english_score))

array([ True,  True,  True,  True,  True,  True])

In [6]:
np.logical_and(np.greater(chinese_score, math_score),np.greater(chinese_score, english_score))

array([ True,  True,  True,  True,  True,  True])